steps:
  # Step 1: Build the project using Maven
  - name: 'maven:3.8.1-jdk-8'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests=false']

  # Step 2: Build Docker image with a custom tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:latest', '.'] # Use 'latest' as the image tag

  # Step 3: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:latest'] # Push the image tagged with 'latest'

  # Step 4: Deploy to Kubernetes using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']

# Define the image output (this will be uploaded to GCR)
images:
  - 'gcr.io/$PROJECT_ID/my-app:latest'

substitutions:
  _IMAGE_TAG: 'latest'