apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: test-ws  # Define the namespace
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: gcr.io/marketcheck-gcp/my-app:latest
          command: [ "java" ]  # Command to run
          args: [ "-Xmx50m", "-jar", "/usr/service/local/SimpleJavaProject-1.0-SNAPSHOT-jar-with-dependencies.jar" ]
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          imagePullPolicy: Always
      nodeSelector:
        nodeType: par  # Define node selector
      tolerations:
        - key: type
          operator: Equal
          value: par
          effect: NoSchedule